package com.instirepo.app.extras;

public interface AppConstants {

	public int Z_RECYCLER_VIEW_ITEM_NORMAL = 0;
	public int Z_RECYCLER_VIEW_ITEM_LOADING = 1;
	
	public String Z_USER_PROFILE_VIEWED_BY_OTHER_BACKSTACK_ENTRY_TAG = "Z_USER_PROFILE_VIEWED_BY_OTHER_BACKSTACK_ENTRY_TAG";
	public String Z_COMMENT_FRAGMENT_BACKSTACK_ENTRY_TAG = "Z_COMMENT_FRAGMENT_BACKSTACK_ENTRY_TAG";

}
