package com.instirepo.app.extras;

public interface AppConstants {

	public int Z_RECYCLER_VIEW_ITEM_NORMAL = 0;
	public int Z_RECYCLER_VIEW_ITEM_LOADING = 1;

	public final String Z_USER_PROFILE_VIEWED_BY_OTHER_BACKSTACK_ENTRY_TAG = "Z_USER_PROFILE_VIEWED_BY_OTHER_BACKSTACK_ENTRY_TAG";
	public final String Z_COMMENT_FRAGMENT_BACKSTACK_ENTRY_TAG = "Z_COMMENT_FRAGMENT_BACKSTACK_ENTRY_TAG";
	public final String Z_USER_PROFILE_VIEWED_BY_OTHER_BACKSTACK_ENTRY_TAG_FROM_COMMENT_LIST_ADAPTER = "Z_USER_PROFILE_VIEWED_BY_OTHER_BACKSTACK_ENTRY_TAG_FROM_COMMENT_LIST_ADAPTER";
	public final String Z_HOME_ACTIVITY_SLECT_CATEGORY_FRAGMENT_TAG = "Z_HOME_ACTIVITY_SLECT_CATEGORY_FRAGMENT_TAG";

	public int Z_CATEGORY_TYPE_UNKNOWN = 0;
	public int Z_CATEGORY_TYPE_EVENT = 1;
	public int Z_CATEGORY_TYPE_PLACEMENT = 2;
	public int Z_CATEGORY_TYPE_POLLS = 3;

	public int Z_VISIBILIY_BRANCH = 1;
	public int Z_VISIBILIY_BATCH = 2;
	public int Z_VISIBILIY_YEAR = 3;
	public int Z_VISIBILIY_TEACHER = 4;

	public int Z_USER_PROFILE_ITEM_HEADER = 2;

	public int Z_MESSAGE_LIST_TYPE_LAODING = 1;
	public int Z_MESSAGE_LIST_TYPE_CHAT_BY_USER = 2;
	public int Z_MESSAGE_LIST_TYPE_CHAT_BY_PERSON = 3;

	public static int Z_REQUEST_CODE_MESSAGES_ACTIVITY = 4578;

	public static int Z_CREATE_POST_PUBLIC = 0;
	public static int Z_CREATE_POST_SELECTED_PEOPLE = 2;
	public static int Z_CREATE_POST_SAVED_COLLECTION = 1;
}
