package com.instirepo.app.extras;

public interface AppConstants {

	public int Z_RECYCLER_VIEW_ITEM_NORMAL = 0;
	public int Z_RECYCLER_VIEW_ITEM_LOADING = 1;

	public String Z_USER_PROFILE_VIEWED_BY_OTHER_BACKSTACK_ENTRY_TAG = "Z_USER_PROFILE_VIEWED_BY_OTHER_BACKSTACK_ENTRY_TAG";
	public String Z_COMMENT_FRAGMENT_BACKSTACK_ENTRY_TAG = "Z_COMMENT_FRAGMENT_BACKSTACK_ENTRY_TAG";

	public int Z_CATEGORY_TYPE_UNKNOWN = 0;
	public int Z_CATEGORY_TYPE_EVENT = 1;
	public int Z_CATEGORY_TYPE_PLACEMENT = 2;
	public int Z_CATEGORY_TYPE_POLLS = 3;

	public int Z_VISIBILIY_BRANCH = 1;
	public int Z_VISIBILIY_BATCH = 2;
	public int Z_VISIBILIY_YEAR = 3;
	public int Z_VISIBILIY_TEACHER = 4;
}
